#!/usr/bin/env python3
"""Build site/docs/<slug>/data.js and the library lists from docs/*/meta.json + OCR md.

Docs whose meta.json has "publish": true go into site/library.js (deployed to GitHub Pages).
All docs go into site/library.preview.js (git-ignored, local preview only), and unpublished
docs are listed in a generated block of .gitignore so they never get committed."""
import json
import re
import sys
from pathlib import Path

import pymupdf

ROOT = Path(__file__).resolve().parent.parent
SLUG_RE = re.compile(r"^[a-z0-9-]+$")
MISSING = "〔尚未辨識〕"

library = []
for meta_path in sorted((ROOT / "docs").glob("*/meta.json")):
    slug = meta_path.parent.name
    if not SLUG_RE.match(slug):
        sys.exit(f"invalid slug {slug!r}: must match ^[a-z0-9-]+$")
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    pdf = pymupdf.open(ROOT / meta["pdf"])
    pages = []
    for i, page in enumerate(pdf, start=1):
        md_path = meta_path.parent / "ocr" / f"page_{i:03d}.md"
        md = md_path.read_text(encoding="utf-8") if md_path.exists() else MISSING
        pages.append({"n": i, "img": f"docs/{slug}/pages/page_{i:03d}.jpg",
                      "w": int(page.rect.width), "h": int(page.rect.height), "md": md})
    doc = {"slug": slug, "title": meta["title"], "subtitle": meta.get("subtitle", ""), "pages": pages}
    out = ROOT / "site" / "docs" / slug
    out.mkdir(parents=True, exist_ok=True)
    (out / "data.js").write_text("window.DOC = " + json.dumps(doc, ensure_ascii=False) + ";\n", encoding="utf-8")
    library.append((meta.get("order", 0), meta.get("publish", False), {"slug": slug, "title": meta["title"],
                    "subtitle": meta.get("subtitle", ""), "pages": len(pages),
                    "cover": f"docs/{slug}/cover.jpg"}))
    print(f"{slug}: {len(pages)} pages")

library.sort(key=lambda t: t[0])


def write_library(name, docs):
    (ROOT / "site" / name).write_text(
        "window.LIBRARY = " + json.dumps(docs, ensure_ascii=False) + ";\n", encoding="utf-8")


published = [d for _, pub, d in library if pub]
write_library("library.js", published)
write_library("library.preview.js", [d for _, _, d in library])
print(f"library.js: {len(published)} published / library.preview.js: {len(library)} docs")

# Keep unpublished docs out of git (and therefore off GitHub Pages).
BEGIN, END = "# >>> unpublished docs (generated by tools/build.py)", "# <<< unpublished docs"
gi_path = ROOT / ".gitignore"
gi = gi_path.read_text(encoding="utf-8")
gi = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", gi, flags=re.S).rstrip("\n") + "\n"
private = [d["slug"] for _, pub, d in library if not pub]
if private:
    gi += BEGIN + "\n" + "".join(f"docs/{s}/\nsite/docs/{s}/\n" for s in private) + END + "\n"
gi_path.write_text(gi, encoding="utf-8")
